const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.MoveTo,
		C3.Behaviors.LOS,
		C3.Plugins.Button,
		C3.Plugins.Timeline,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareFrameTag,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Text.Acts.SetText
	];
};
self.C3_JsPropNameTable = [
	{Keyboard: 0},
	{Solid: 0},
	{Tilemap: 0},
	{startX: 0},
	{startY: 0},
	{State: 0},
	{StatusMadera: 0},
	{StatusOro: 0},
	{Platform: 0},
	{MoverA: 0},
	{LíneaDeVisión: 0},
	{Sprite: 0},
	{arbolstartX: 0},
	{arbolstartY: 0},
	{arbol: 0},
	{Button_Madera: 0},
	{timeline: 0},
	{piedrastartX: 0},
	{Home: 0},
	{CantidadOro: 0},
	{Totaloro: 0},
	{Button_oro: 0},
	{OroStarX: 0},
	{ORO: 0},
	{Audio: 0},
	{Cantidadmadera: 0},
	{Totalmadera: 0},
	{AlmacenamientoLocal: 0}
];

self.InstanceType = {
	Keyboard: class extends self.IInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Sprite: class extends self.ISpriteInstance {},
	arbol: class extends self.ISpriteInstance {},
	Button_Madera: class extends self.IButtonInstance {},
	timeline: class extends self.IInstance {},
	Home: class extends self.ISpriteInstance {},
	Totaloro: class extends self.ITextInstance {},
	Button_oro: class extends self.IButtonInstance {},
	ORO: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Totalmadera: class extends self.ITextInstance {},
	AlmacenamientoLocal: class extends self.IInstance {}
}